name: PALATA_RaidPlugin
version: '1.0-SNAPSHOT'
main: org.palata_raidplugin.palata_raidplugin.PALATA_RaidPlugin
api-version: 1.19
commands:
  setraidbase:
    description: Ставим центр базы.
    usage: /<command> <team>
  openraid:
    description: Открывает возможность рейда.
    usage: /<command>
  cancelraid:
    description: Отменяет рейд.
    usage: /<command>
  joinraid:
    description: Присоединяемся к рейду.
    usage: /<command>
  startraid:
    description: Начинаем рейд.
    usage: /<command>
  raid:
    description: Включение и выключение рейдов.
    usage: /<command> [on|off|info]