name: PALATA_RaidPlugin
version: '${project.version}'
main: org.palata_raidplugin.palata_raidplugin.PALATA_RaidPlugin
api-version: 1.19
commands:
  setraidbase:
    description: Ставим центр базы.
    usage: /<command>
  sethomebase:
    description: Ставим центр дома.
    usage: /<command>
  privatecheck:
    description: Проверка на то, в каком регионе вы находитесь.
    usage: /<command>
  openraid:
    description: Открывает возможность рейда.
    usage: /<command>
  cancelraid:
    description: Отменяет рейд.
    usage: /<command>
  joinraid:
    description: Присоединяемся к рейду.
    usage: /<command>
  startraid:
    description: Начинаем рейд.
    usage: /<command>
  raid:
    description: Включение и выключение рейдов.
    usage: /<command> [on|off|info]
  getenemyraidbasecoords:
    description: Получение координат вражеского Нексуса.
    usage: /<command>