name: PALATA_BanPlayerOnDeath
version: '1.0-SNAPSHOT'
main: org.palata_banplayerondeath.palata_banplayerondeath.PALATA_BanPlayerOnDeath
api-version: 1.19
commands:
  deathban:
    description: Управление системой DeathBan
    usage: >
      /deathban on
      /deathban off
      /deathban info
      /deathban schedule <minutes>
      /deathban unban <player>