name: PALATA_BanPlayerOnDeath
version: '${project.version}'
main: org.palata_banplayerondeath.palata_banplayerondeath.PALATA_BanPlayerOnDeath
api-version: 1.19
commands:
  deathban:
    description: Включает или выключает бан за смерть
    usage: /<command> [on|off|info]